### ISSUE TITLE
Color Picker modal window is broken in Yosemite

### ISSUE THREAD

**Issue by Down10** [textmate/css.tmbundle#16]
Mac OS X Yosemite has rearranged the modal window to the Color Picker, and this is now affects the ability to use the eye dropper or the color wells, as they now conflict with the position of the Cancel and OK buttons. Clicking the eye dropper does nothing until hitting cancel, upon which the eye dropper tool is active.

[Example](https://www.dropbox.com/s/495rlreli2ph49t/Screenshot%202014-11-17%2009.35.57.PNG?dl=0)

**Comment by kramsee** [comment]
Seems to be fixed for me. I think this can be closed.

**Comment by infininight** [comment]
Indeed, it works without issue for me here now.
